services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: ghcr.io/dgox16/easy-diceware-frontend:latest
    container_name: easy-diceware-frontend-container
    restart: unless-stopped
    ports:
      - "8003:80"

  api:
    image: ghcr.io/dgox16/easy-diceware-api:latest
    container_name: easy-diceware-api-container
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - api_storage_easy_diceware:/var/www/storage
    depends_on:
      - db
    env_file:
      - ./api/.env.produccion

  api_nginx:
    image: nginx:1.29.1-alpine
    container_name: easy-diceware-api-nginx
    restart: unless-stopped
    ports:
      - "8004:80"
    volumes:
      - ./nginx.api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: postgres:17-alpine
    container_name: easy-diceware-db-container
    restart: unless-stopped
    volumes:
      - postgres_data_easy_diceware:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres_data_easy_diceware:
  api_storage_easy_diceware:
